name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes as submodules
          fetch-depth: 0    # Fetch all history for proper versioning

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.0'  # Specify the Hugo version you need

      - name: Build Hugo Site
        run: hugo --minify
        env:
          HUGO_ENVIRONMENT: production  # Set Hugo environment to production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Directory containing Hugo's generated static files
